services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: workout-api
    image: saifbiobaku/workout-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/workout_app.db
      OTEL_SERVICE_NAME: workout-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_PYTHON_LOG_CORRELATION: "true"
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
      LOG_LEVEL: INFO
    volumes:
      - workout_data:/data
    depends_on:
      - otel-lgtm
    restart: unless-stopped

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    ports:
      - "3010:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - otel_lgtm_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: workout-web
    image: saifbiobaku/workout-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  workout_data:
  otel_lgtm_data:
