services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: workout-api
    image: saifbiobaku/workout-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/workout_app.db
    volumes:
      - workout_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: workout-web
    image: saifbiobaku/workout-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  workout_data:
