apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workout-api-data
  namespace: workout
  labels:
    app.kubernetes.io/name: workout-api
    app.kubernetes.io/part-of: workout-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
