apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-api-config
  namespace: workout
  labels:
    app.kubernetes.io/name: workout-api
    app.kubernetes.io/part-of: workout-app
data:
  AUTH_ALGORITHM: HS256
  DATABASE_URL: sqlite:////data/workout_app.db
