apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
  namespace: workout
  labels:
    app.kubernetes.io/name: otel-lgtm
    app.kubernetes.io/part-of: workout-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: otel-lgtm
  ports:
    - name: grafana
      port: 3010
      targetPort: grafana
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
