apiVersion: v1
kind: Service
metadata:
  name: workout-web
  namespace: workout
  labels:
    app.kubernetes.io/name: workout-web
    app.kubernetes.io/part-of: workout-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: workout-web
  ports:
    - name: http
      port: 3000
      targetPort: http
